# change the followings to match your Github username and repo name
baseurl: "/wraymscott" # the name of your github repo
url: "https://wraymscott.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Wray Scott"
description: A website to showcase some of my projects!

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Wray M. Scott IV
author-bio: WSU CS student, Programmer, 3d Modeler  # change to false to hide
author-image: headshot.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: blog
  permalink: blog
- text: Contact
  permalink: contact

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/wraymscott
linkedin: https://www.linkedin.com/in/wray-scott-1b1a91386/
medium: false
google-scholar: false
email: wraymscott@gmail.com
youtube: https://youtube.com/@wraymscott?si=CwOAvn6i-V0zKadS

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag

future: true